### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by nc-olnk** [szymciogrosik/script-control-panel#2]
Make it possible to run buenos dias in dark mode 
![image](https://github.com/nc-szyg/dias-service-runner/assets/161462546/4a7d15b9-2efc-4888-8c51-07cc731f774d)

**Comment by szymciogrosik** [comment]
Unfortunately this is a default windows navbar and I cannot enable dark mode. You can change your windows settings to change this navbar colour:
![image](https://github.com/user-attachments/assets/b256ef63-7482-428a-bae9-55ada57be619)
I hope it will solve the issue
